"""
Supabase access for the worker — service-role key, bypasses RLS. This
is the ONE place in the whole pipeline allowed to bypass RLS, because
it's the only thing that legitimately needs to (a) read an uploaded
file from any user's folder in the content-uploads bucket, and
(b) write draft rows that no client-facing insert policy grants (see
mathora_schema_content_pipeline_patch.sql's comments on both).
"""

from __future__ import annotations
import tempfile
from pathlib import Path
from supabase import create_client, Client
from .config import settings
from .schema import GenerationResult

_client: Client = create_client(settings.supabase_url, settings.supabase_service_role_key)

STORAGE_BUCKET = "content-uploads"


def download_upload_file(storage_path: str) -> Path:
    data = _client.storage.from_(STORAGE_BUCKET).download(storage_path)
    suffix = Path(storage_path).suffix or ".bin"
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    tmp.write(data)
    tmp.close()
    return Path(tmp.name)


def update_upload_status(upload_id: str, status: str, error_message: str | None = None) -> None:
    payload = {"status": status, "updated_at": "now()"}
    if error_message is not None:
        payload["error_message"] = error_message
    _client.table("content_uploads").update(payload).eq("id", upload_id).execute()


def _get_or_create_ai_lesson(topic_id: str) -> str:
    """
    worked_examples.lesson_id is NOT NULL in mathora_schema.sql, but
    the upload flow only asks the admin to pick a topic, not a
    specific lesson (keeping that one form field simpler). Rather than
    forcing a lesson choice in the UI for what's meant to be a quick
    upload, find-or-create a single holding lesson per topic for
    AI-generated worked examples to attach to. It's just as much a
    'draft' as the worked examples themselves — nothing under it is
    visible to students until reviewed.
    """
    existing = (
        _client.table("lessons")
        .select("id")
        .eq("topic_id", topic_id)
        .eq("title", "AI-Generated Worked Examples")
        .limit(1)
        .execute()
    )
    if existing.data:
        return existing.data[0]["id"]

    created = (
        _client.table("lessons")
        .insert(
            {
                "topic_id": topic_id,
                "title": "AI-Generated Worked Examples",
                "summary": "Auto-generated worked examples pending admin review.",
                "content_body": "Generated by content-worker from an uploaded document. See attached worked examples.",
                "order_index": 999,
            }
        )
        .execute()
    )
    return created.data[0]["id"]


def insert_generated_content(upload_id: str, topic_id: str, result: GenerationResult) -> tuple[list[str], list[str]]:
    question_ids: list[str] = []
    worked_example_ids: list[str] = []

    if result.questions:
        rows = [
            {
                "topic_id": topic_id,
                "question_text": q.question_text,
                "question_latex": q.question_latex,
                "option_a": q.option_a,
                "option_b": q.option_b,
                "option_c": q.option_c,
                "option_d": q.option_d,
                "correct_letter": q.correct_letter,
                "difficulty": q.difficulty,
                "exam_type": q.exam_type,
                "explanation": q.explanation,
                "exam_shortcut": q.exam_shortcut,
                "status": "draft",
            }
            for q in result.questions
        ]
        inserted = _client.table("questions").insert(rows).execute()
        question_ids = [row["id"] for row in inserted.data]

    if result.worked_examples:
        lesson_id = _get_or_create_ai_lesson(topic_id)
        rows = [
            {
                "lesson_id": lesson_id,
                "title": we.title,
                "problem_statement": we.problem_statement,
                "solution_steps": we.solution_steps,
                "exam_shortcut": we.exam_shortcut,
                "common_trap_warning": we.common_trap_warning,
                "status": "draft",
            }
            for we in result.worked_examples
        ]
        inserted = _client.table("worked_examples").insert(rows).execute()
        worked_example_ids = [row["id"] for row in inserted.data]

    _client.table("content_uploads").update(
        {
            "status": "ready_for_review",
            "generated_question_ids": question_ids,
            "generated_worked_example_ids": worked_example_ids,
            "updated_at": "now()",
        }
    ).eq("id", upload_id).execute()

    return question_ids, worked_example_ids


def get_upload(upload_id: str) -> dict:
    result = _client.table("content_uploads").select("*").eq("id", upload_id).single().execute()
    return result.data
