"""
Supabase access for the worker — service-role key, bypasses RLS. This
is the ONE place in the whole pipeline allowed to bypass RLS, because
it's the only thing that legitimately needs to (a) read an uploaded
file from any user's folder in the content-uploads bucket, and
(b) write draft rows that no client-facing insert policy grants (see
mathora_schema_content_pipeline_patch.sql's comments on both).
"""

from __future__ import annotations
import tempfile
from pathlib import Path
from supabase import create_client, Client
from .config import settings
from .schema import GenerationResult

_client: Client = create_client(settings.supabase_url, settings.supabase_service_role_key)

STORAGE_BUCKET = "content-uploads"
DIAGRAM_IMAGE_BUCKET = "lesson-diagrams"


def download_upload_file(storage_path: str) -> Path:
    data = _client.storage.from_(STORAGE_BUCKET).download(storage_path)
    suffix = Path(storage_path).suffix or ".bin"
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    tmp.write(data)
    tmp.close()
    return Path(tmp.name)


def upload_extracted_image(upload_id: str, local_path: Path, index: int) -> str:
    """
    Uploads a figure parser.py pulled out of the source document to
    the public lesson-diagrams bucket and returns its public URL, for
    referencing via diagram_type='image' (see lib/diagramTypes.ts's
    ImageDiagramData on the web side).
    """
    storage_path = f"{upload_id}/fig-{index}.png"
    data = local_path.read_bytes()
    _client.storage.from_(DIAGRAM_IMAGE_BUCKET).upload(
        storage_path, data, {"content-type": "image/png", "upsert": "true"}
    )
    return _client.storage.from_(DIAGRAM_IMAGE_BUCKET).get_public_url(storage_path)


def update_upload_status(upload_id: str, status: str, error_message: str | None = None) -> None:
    payload = {"status": status, "updated_at": "now()"}
    if error_message is not None:
        payload["error_message"] = error_message
    _client.table("content_uploads").update(payload).eq("id", upload_id).execute()


def _get_or_create_ai_lesson(topic_id: str) -> str:
    """
    worked_examples.lesson_id is NOT NULL in mathora_schema.sql, but
    the upload flow only asks the admin to pick a topic, not a
    specific lesson (keeping that one form field simpler). Rather than
    forcing a lesson choice in the UI for what's meant to be a quick
    upload, find-or-create a single holding lesson per topic for
    AI-generated worked examples to attach to. It's just as much a
    'draft' as the worked examples themselves — nothing under it is
    visible to students until reviewed.
    """
    existing = (
        _client.table("lessons")
        .select("id")
        .eq("topic_id", topic_id)
        .eq("title", "AI-Generated Worked Examples")
        .limit(1)
        .execute()
    )
    if existing.data:
        return existing.data[0]["id"]

    created = (
        _client.table("lessons")
        .insert(
            {
                "topic_id": topic_id,
                "title": "AI-Generated Worked Examples",
                "summary": "Auto-generated worked examples pending admin review.",
                "content_body": "Generated by content-worker from an uploaded document. See attached worked examples.",
                "order_index": 999,
            }
        )
        .execute()
    )
    return created.data[0]["id"]


def insert_generated_content(
    upload_id: str, topic_id: str, result: GenerationResult, extracted_image_urls: list[str] | None = None
) -> tuple[list[str], list[str]]:
    """
    extracted_image_urls: figures parser.py actually pulled out of the
    source document (already uploaded by main.py). When present, the
    first one is attached to the first worked example that doesn't
    already have its own generated diagram — deterministically, in
    this orchestration layer, rather than asking the LLM to reference
    an opaque URL it wasn't shown clearly. A real source figure takes
    priority over a generated placeholder diagram_type, but never
    overwrites one the model already produced.
    """
    question_ids: list[str] = []
    worked_example_ids: list[str] = []

    if result.questions:
        rows = [
            {
                "topic_id": topic_id,
                "question_text": q.question_text,
                "question_latex": q.question_latex,
                "option_a": q.option_a,
                "option_b": q.option_b,
                "option_c": q.option_c,
                "option_d": q.option_d,
                "correct_letter": q.correct_letter,
                "difficulty": q.difficulty,
                "exam_type": q.exam_type,
                "explanation": q.explanation,
                "exam_shortcut": q.exam_shortcut,
                "diagram_type": q.diagram_type,
                "diagram_data": q.diagram_data,
                "status": "draft",
            }
            for q in result.questions
        ]
        inserted = _client.table("questions").insert(rows).execute()
        question_ids = [row["id"] for row in inserted.data]

    if result.worked_examples:
        lesson_id = _get_or_create_ai_lesson(topic_id)
        remaining_images = list(extracted_image_urls or [])
        rows = []
        for we in result.worked_examples:
            diagram_type = we.diagram_type
            diagram_data = we.diagram_data
            if diagram_type == "none" and remaining_images:
                diagram_type = "image"
                diagram_data = {"imageUrl": remaining_images.pop(0)}

            rows.append(
                {
                    "lesson_id": lesson_id,
                    "title": we.title,
                    "problem_statement": we.problem_statement,
                    "solution_steps": we.solution_steps,
                    "exam_shortcut": we.exam_shortcut,
                    "common_trap_warning": we.common_trap_warning,
                    "real_life_context": we.real_life_context or None,
                    "diagram_type": diagram_type,
                    "diagram_data": diagram_data,
                    "status": "draft",
                }
            )
        inserted = _client.table("worked_examples").insert(rows).execute()
        worked_example_ids = [row["id"] for row in inserted.data]

    _client.table("content_uploads").update(
        {
            "status": "ready_for_review",
            "generated_question_ids": question_ids,
            "generated_worked_example_ids": worked_example_ids,
            "updated_at": "now()",
        }
    ).eq("id", upload_id).execute()

    return question_ids, worked_example_ids


def get_upload(upload_id: str) -> dict:
    result = _client.table("content_uploads").select("*").eq("id", upload_id).single().execute()
    return result.data


# ------------------------------------------
# Syllabus-driven batch generation (scripts/seed_from_syllabus.py).
# Reuses the same content_uploads/review pipeline as the file-upload
# path above, so a syllabus-generated topic shows up in the exact same
# admin "Pending Review" tab — just with no actual file behind it
# (storage_path is a descriptive placeholder, never read back).
# ------------------------------------------

def list_topics_for_subject(subject: str) -> list[dict]:
    """subject: 'Mathematics' or 'Further Mathematics' (curricula.subject)."""
    result = (
        _client.table("topics")
        .select("id, title, description, class_level, term, order_index, curricula!inner(subject)")
        .eq("curricula.subject", subject)
        .order("class_level")
        .order("term")
        .order("order_index")
        .execute()
    )
    return result.data


def topic_has_generated_content(topic_id: str) -> bool:
    """
    True if a content_uploads row already exists for this topic and
    reached ready_for_review/published — lets the batch script skip
    topics it already covered on a previous (possibly interrupted) run,
    rather than re-spending API calls generating duplicates.
    """
    result = (
        _client.table("content_uploads")
        .select("id")
        .eq("topic_id", topic_id)
        .in_("status", ["ready_for_review", "published"])
        .limit(1)
        .execute()
    )
    return len(result.data) > 0


def create_syllabus_upload_placeholder(topic_id: str, topic_title: str, question_count: int) -> dict:
    result = (
        _client.table("content_uploads")
        .insert(
            {
                "uploaded_by": None,  # system-generated, not a specific human uploader
                "topic_id": topic_id,
                "original_filename": f"[syllabus] {topic_title}",
                "storage_path": f"syllabus/{topic_id}",  # never read back — no real file behind this row
                "requested_question_count": question_count,
                "status": "generating",
            }
        )
        .execute()
    )
    return result.data[0]
